# Generated by Django 6.0.1 on 2026-02-07 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='stores', to='marketing.contact'),
        ),
        migrations.AddField(
            model_name='store',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='group.group', verbose_name='Grupo'),
        ),
    ]
